sonar.projectKey=Todo-list
sonar.sources=JS/
sonar.host.url=http://localhost:9000
sonar.login=sqp_98d82aecacc8902f3e151e41817fafcf50149f3f
sonar.tests=tests/
sonar.javascript.lcov.reportPaths=coverage/lcov.info